openapi: 3.0.3
info:
  title: App Review Browser API
  version: 1.0.0
  description: API for browsing iOS app reviews.
paths:
  /reviews:
    get:
      summary: Get app reviews
      description: Retrieve a list of app reviews.
      parameters:
        - name: appId
          in: query
          required: true
          schema:
            type: string
          description: The ID of the app to fetch reviews for.
      responses:
        '200':
          description: A list of app reviews.
          content:
            application/json:
              schema:
                type: object
                properties:
                  reviews:
                    type: array
                    items:
                      type: object
                      properties:
                        author:
                          type: string
                        rating:
                          type: integer
                        title:
                          type: string
                        content:
                          type: string
                        datePublished:
                          type: string
                          format: date-time
        '400':
          description: Invalid request parameters.
        '404':
          description: App not found.